//
// AirRefuelEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct AirRefuelEvent: Codable, JSONEncodable, Hashable {

    /**  */
    public var dateCreated: Date?
    /**  */
    public var plugs: Int?
    /**  */
    public var quantity: Double?

    public init(dateCreated: Date? = nil, plugs: Int? = nil, quantity: Double? = nil) {
        self.dateCreated = dateCreated
        self.plugs = plugs
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dateCreated
        case plugs
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dateCreated, forKey: .dateCreated)
        try container.encodeIfPresent(plugs, forKey: .plugs)
        try container.encodeIfPresent(quantity, forKey: .quantity)
    }
}

