//
// AnalyticsResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An analytics object */
public struct AnalyticsResult: Codable, JSONEncodable, Hashable {

    /** Name of result */
    public var name: String
    /** Number of results associated with name */
    public var total: Int

    public init(name: String, total: Int) {
        self.name = name
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(total, forKey: .total)
    }
}

