//
// AnalyticsQueryTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Types of analytics queries for Analytics History */
public enum AnalyticsQueryTypeEnum: String, Codable, CaseIterable {
    case minute = "MINUTE"
    case hour = "HOUR"
    case day = "DAY"
    case month = "MONTH"
    case year = "YEAR"
    case today = "TODAY"
}
