//
// ApplicationRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List of application roles */
public struct ApplicationRole: Codable, JSONEncodable, Hashable {

    /** Application role id */
    public var id: Int64
    /** Application role name */
    public var name: String
    /** A list of application permissions */
    public var permissions: [ApplicationPermission]

    public init(id: Int64, name: String, permissions: [ApplicationPermission]) {
        self.id = id
        self.name = name
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(permissions, forKey: .permissions)
    }
}

