//
// ApplicationPermission.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List of application permissions */
public struct ApplicationPermission: Codable, JSONEncodable, Hashable {

    /** Application permission name */
    public var applicationPermissionName: String
    /** Application permission id */
    public var applicationPermissionId: Int

    public init(applicationPermissionName: String, applicationPermissionId: Int) {
        self.applicationPermissionName = applicationPermissionName
        self.applicationPermissionId = applicationPermissionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case applicationPermissionName
        case applicationPermissionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(applicationPermissionName, forKey: .applicationPermissionName)
        try container.encode(applicationPermissionId, forKey: .applicationPermissionId)
    }
}

