//
// ArmsFlightRecordStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ArmsFlightRecordStatus: Codable, JSONEncodable, Hashable {

    /**  */
    public var id: UUID
    public var status: ArmsUploadStatusEnum
    /**  */
    public var sortieId: UUID
    /**  */
    public var flightRecordStatusMessages: [ArmsFlightRecordStatusMessage]

    public init(id: UUID, status: ArmsUploadStatusEnum, sortieId: UUID, flightRecordStatusMessages: [ArmsFlightRecordStatusMessage]) {
        self.id = id
        self.status = status
        self.sortieId = sortieId
        self.flightRecordStatusMessages = flightRecordStatusMessages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
        case sortieId
        case flightRecordStatusMessages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(sortieId, forKey: .sortieId)
        try container.encode(flightRecordStatusMessages, forKey: .flightRecordStatusMessages)
    }
}

