//
// ArmsUploadStatusEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum ArmsUploadStatusEnum: String, Codable, CaseIterable {
    case received = "RECEIVED"
    case submitted = "SUBMITTED"
    case incomplete = "INCOMPLETE"
    case manuallyAdded = "MANUALLY_ADDED"
}
