//
// ArmsProgramCodeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ArmsProgramCodeEnum: String, Codable, CaseIterable {
    case gt = "GT"
    case tt = "TT"
    case md = "MD"
    case ue = "UE"
    case ft = "FT"
    case ac = "AC"
    case st = "ST"
    case ao = "AO"
    case pc = "PC"
}
