//
// ArmsStatusListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Object containing statuses for all beans and flight records for a mission */
public struct ArmsStatusListResult: Codable, JSONEncodable, Hashable {

    /**  */
    public var beanStatuses: [ArmsBeanStatus]
    /**  */
    public var flightRecordStatuses: [ArmsFlightRecordStatus]

    public init(beanStatuses: [ArmsBeanStatus], flightRecordStatuses: [ArmsFlightRecordStatus]) {
        self.beanStatuses = beanStatuses
        self.flightRecordStatuses = flightRecordStatuses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case beanStatuses
        case flightRecordStatuses
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(beanStatuses, forKey: .beanStatuses)
        try container.encode(flightRecordStatuses, forKey: .flightRecordStatuses)
    }
}

