//
// BoxIdentifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Names for the Big Board custom content boxes */
public enum BoxIdentifier: String, Codable, CaseIterable {
    case bottom1 = "BOTTOM_1"
    case bottom2 = "BOTTOM_2"
    case bottomRight = "BOTTOM_RIGHT"
    case right1 = "RIGHT_1"
    case upperRight = "UPPER_RIGHT"
}
