//
// ChannelMembersRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ChannelMembersRequest: Codable, JSONEncodable, Hashable {

    /**  */
    public var eventId: UUID
    /**  */
    public var aircrewIds: [UUID]
    /**  */
    public var channelId: String
    /**  */
    public var eventTypeId: Int?

    public init(eventId: UUID, aircrewIds: [UUID], channelId: String, eventTypeId: Int? = nil) {
        self.eventId = eventId
        self.aircrewIds = aircrewIds
        self.channelId = channelId
        self.eventTypeId = eventTypeId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventId
        case aircrewIds
        case channelId
        case eventTypeId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventId, forKey: .eventId)
        try container.encode(aircrewIds, forKey: .aircrewIds)
        try container.encode(channelId, forKey: .channelId)
        try container.encodeIfPresent(eventTypeId, forKey: .eventTypeId)
    }
}

