//
// ChannelResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ChannelResponseItem: Codable, JSONEncodable, Hashable {

    /**  */
    public var userId: UUID
    /**  */
    public var message: String?

    public init(userId: UUID, message: String? = nil) {
        self.userId = userId
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

