//
// CommonApiComponentDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct CommonApiComponentDetails: Codable, JSONEncodable, Hashable {

    public var statusCode: Int?
    public var lastUpTime: Date?

    public init(statusCode: Int? = nil, lastUpTime: Date? = nil) {
        self.statusCode = statusCode
        self.lastUpTime = lastUpTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case statusCode
        case lastUpTime = "Last Up Time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(lastUpTime, forKey: .lastUpTime)
    }
}

