//
// CommonApiComponent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Single component of Common API that reports health */
public struct CommonApiComponent: Codable, JSONEncodable, Hashable {

    /**  */
    public var status: String?
    public var details: CommonApiComponentDetails?

    public init(status: String? = nil, details: CommonApiComponentDetails? = nil) {
        self.status = status
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(details, forKey: .details)
    }
}

