//
// CrewPositionEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum CrewPositionEnum: String, Codable, CaseIterable {
    case pilot = "PILOT"
    case loadmaster = "LOADMASTER"
    case pilotSlashLoadmaster = "PILOT/LOADMASTER"
}
