//
// CurrencyTag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Currency tag information     */
public struct CurrencyTag: Codable, JSONEncodable, Hashable {

    /** Name of currency tag */
    public var name: String
    /** Currencies associated with this tag */
    public var currencies: [UUID]
    /** uuid of the currency tag */
    public var currencyTagId: UUID?
    /** id of organization that tag belongs to */
    public var organizationId: UUID

    public init(name: String, currencies: [UUID], currencyTagId: UUID? = nil, organizationId: UUID) {
        self.name = name
        self.currencies = currencies
        self.currencyTagId = currencyTagId
        self.organizationId = organizationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case currencies
        case currencyTagId
        case organizationId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(currencies, forKey: .currencies)
        try container.encodeIfPresent(currencyTagId, forKey: .currencyTagId)
        try container.encode(organizationId, forKey: .organizationId)
    }
}

