//
// Currency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** currency pulled from ARMS */
public struct Currency: Codable, JSONEncodable, Hashable {

    /** The name of the task */
    public var name: String
    /** The id of the task */
    public var taskId: String
    /** the possible crew positions for the task */
    public var crewPositions: [String]
    /** uuid of the currency */
    public var currencyId: UUID
    /** id of the currency tag that this currency is assigned to */
    public var currencyTagId: UUID

    public init(name: String, taskId: String, crewPositions: [String], currencyId: UUID, currencyTagId: UUID) {
        self.name = name
        self.taskId = taskId
        self.crewPositions = crewPositions
        self.currencyId = currencyId
        self.currencyTagId = currencyTagId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case taskId
        case crewPositions
        case currencyId
        case currencyTagId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(taskId, forKey: .taskId)
        try container.encode(crewPositions, forKey: .crewPositions)
        try container.encode(currencyId, forKey: .currencyId)
        try container.encode(currencyTagId, forKey: .currencyTagId)
    }
}

