//
// DefaultEventJobRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct DefaultEventJobRole: Codable, JSONEncodable, Hashable {

    /**  */
    public var eventTypeId: Int
    /**  */
    public var jobRoleId: Int
    /**  */
    public var index: Int
    /** UUID of default job role */
    public var id: UUID?
    /** id of user who created the entry */
    public var createdBy: UUID?
    /** id of user who last modified the entry */
    public var lastModifiedBy: UUID?
    /** date of entry creation */
    public var createdDate: Date?
    /** date entry was last modified */
    public var lastModifiedDate: Date?

    public init(eventTypeId: Int, jobRoleId: Int, index: Int, id: UUID? = nil, createdBy: UUID? = nil, lastModifiedBy: UUID? = nil, createdDate: Date? = nil, lastModifiedDate: Date? = nil) {
        self.eventTypeId = eventTypeId
        self.jobRoleId = jobRoleId
        self.index = index
        self.id = id
        self.createdBy = createdBy
        self.lastModifiedBy = lastModifiedBy
        self.createdDate = createdDate
        self.lastModifiedDate = lastModifiedDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventTypeId
        case jobRoleId
        case index
        case id
        case createdBy
        case lastModifiedBy
        case createdDate
        case lastModifiedDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventTypeId, forKey: .eventTypeId)
        try container.encode(jobRoleId, forKey: .jobRoleId)
        try container.encode(index, forKey: .index)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(lastModifiedBy, forKey: .lastModifiedBy)
        try container.encodeIfPresent(createdDate, forKey: .createdDate)
        try container.encodeIfPresent(lastModifiedDate, forKey: .lastModifiedDate)
    }
}

