//
// EventField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct EventField: Codable, JSONEncodable, Hashable {

    /**  */
    public var id: UUID?
    /**  */
    public var fieldType: String?
    /** label for field */
    public var name: String?
    /**  */
    public var active: Bool?
    /**  */
    public var eventTypeId: Int?
    /**  */
    public var index: Int
    /** id of user who created the entry */
    public var createdBy: UUID?
    /** id of user who last modified the entry */
    public var lastModifiedBy: UUID?
    /** date of entry creation */
    public var createdDate: Date?
    /** date entry was last modified */
    public var lastModifiedDate: Date?

    public init(id: UUID? = nil, fieldType: String? = nil, name: String? = nil, active: Bool? = nil, eventTypeId: Int? = nil, index: Int, createdBy: UUID? = nil, lastModifiedBy: UUID? = nil, createdDate: Date? = nil, lastModifiedDate: Date? = nil) {
        self.id = id
        self.fieldType = fieldType
        self.name = name
        self.active = active
        self.eventTypeId = eventTypeId
        self.index = index
        self.createdBy = createdBy
        self.lastModifiedBy = lastModifiedBy
        self.createdDate = createdDate
        self.lastModifiedDate = lastModifiedDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case fieldType
        case name
        case active
        case eventTypeId
        case index
        case createdBy
        case lastModifiedBy
        case createdDate
        case lastModifiedDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(fieldType, forKey: .fieldType)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(active, forKey: .active)
        try container.encodeIfPresent(eventTypeId, forKey: .eventTypeId)
        try container.encode(index, forKey: .index)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(lastModifiedBy, forKey: .lastModifiedBy)
        try container.encodeIfPresent(createdDate, forKey: .createdDate)
        try container.encodeIfPresent(lastModifiedDate, forKey: .lastModifiedDate)
    }
}

