//
// EventGetError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct EventGetError: Codable, JSONEncodable, Hashable {

    /**  */
    public var id: UUID
    /**  */
    public var timestamp: String
    /**  */
    public var principalId: UUID
    /**  */
    public var message: String?

    public init(id: UUID, timestamp: String, principalId: UUID, message: String? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.principalId = principalId
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case principalId
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(principalId, forKey: .principalId)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

