//
// FeatureEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum FeatureEnum: String, Codable, CaseIterable {
    case analyticsLogging = "ANALYTICS_LOGGING"
}
