//
// FeatureResultList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** list result for features in order to not return arrays by the API */
public struct FeatureResultList: Codable, JSONEncodable, Hashable {

    /**  */
    public var result: [Feature]

    public init(result: [Feature]) {
        self.result = result
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case result
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(result, forKey: .result)
    }
}

