//
// FeatureAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FeatureAllOf: Codable, JSONEncodable, Hashable {

    /** uuid of feature */
    public var featureId: UUID
    public var featureName: FeatureEnum
    /** boolean of feature if it is enabled to run or not */
    public var enabled: Bool

    public init(featureId: UUID, featureName: FeatureEnum, enabled: Bool) {
        self.featureId = featureId
        self.featureName = featureName
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case featureId
        case featureName
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(featureId, forKey: .featureId)
        try container.encode(featureName, forKey: .featureName)
        try container.encode(enabled, forKey: .enabled)
    }
}

