//
// FlightTime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct FlightTime: Codable, JSONEncodable, Hashable {

    /**  */
    public var evaluator: Double?
    /**  */
    public var instructor: Double?
    /**  */
    public var other: Double?
    /**  */
    public var primary: Double?
    /**  */
    public var secondary: Double?

    public init(evaluator: Double? = nil, instructor: Double? = nil, other: Double? = nil, primary: Double? = nil, secondary: Double? = nil) {
        self.evaluator = evaluator
        self.instructor = instructor
        self.other = other
        self.primary = primary
        self.secondary = secondary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case evaluator
        case instructor
        case other
        case primary
        case secondary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(evaluator, forKey: .evaluator)
        try container.encodeIfPresent(instructor, forKey: .instructor)
        try container.encodeIfPresent(other, forKey: .other)
        try container.encodeIfPresent(primary, forKey: .primary)
        try container.encodeIfPresent(secondary, forKey: .secondary)
    }
}

