//
// FreeTextLabel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct FreeTextLabel: Codable, JSONEncodable, Hashable {

    public var order: Int
    public var bgColor: String?
    public var highlight: Bool?
    public var value: String

    public init(order: Int, bgColor: String? = nil, highlight: Bool? = nil, value: String) {
        self.order = order
        self.bgColor = bgColor
        self.highlight = highlight
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case order
        case bgColor
        case highlight
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(order, forKey: .order)
        try container.encodeIfPresent(bgColor, forKey: .bgColor)
        try container.encodeIfPresent(highlight, forKey: .highlight)
        try container.encode(value, forKey: .value)
    }
}

