//
// JobRoleCompatibility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct JobRoleCompatibility: Codable, JSONEncodable, Hashable {

    /** Id of job role */
    public var jobRole: Int?
    /** Ids of compatible job roles */
    public var compatibleJobRoles: [Int]?

    public init(jobRole: Int? = nil, compatibleJobRoles: [Int]? = nil) {
        self.jobRole = jobRole
        self.compatibleJobRoles = compatibleJobRoles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobRole
        case compatibleJobRoles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(jobRole, forKey: .jobRole)
        try container.encodeIfPresent(compatibleJobRoles, forKey: .compatibleJobRoles)
    }
}

