//
// JobRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct JobRole: Codable, JSONEncodable, Hashable {

    /**  */
    public var roleType: String
    /**  */
    public var roleName: String
    /**  */
    public var id: Int?
    /**  */
    public var organizationId: UUID
    /**  */
    public var active: Bool
    /** Custom abbreviation of role name for display */
    public var abbreviation: String?
    /** Order of precedence for sorting purposes */
    public var order: Int?
    /** id of user who created the entry */
    public var createdBy: UUID?
    /** id of user who last modified the entry */
    public var lastModifiedBy: UUID?
    /** date of entry creation */
    public var createdDate: Date?
    /** date entry was last modified */
    public var lastModifiedDate: Date?

    public init(roleType: String, roleName: String, id: Int? = nil, organizationId: UUID, active: Bool, abbreviation: String? = nil, order: Int? = nil, createdBy: UUID? = nil, lastModifiedBy: UUID? = nil, createdDate: Date? = nil, lastModifiedDate: Date? = nil) {
        self.roleType = roleType
        self.roleName = roleName
        self.id = id
        self.organizationId = organizationId
        self.active = active
        self.abbreviation = abbreviation
        self.order = order
        self.createdBy = createdBy
        self.lastModifiedBy = lastModifiedBy
        self.createdDate = createdDate
        self.lastModifiedDate = lastModifiedDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roleType
        case roleName
        case id
        case organizationId
        case active
        case abbreviation
        case order
        case createdBy
        case lastModifiedBy
        case createdDate
        case lastModifiedDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(roleType, forKey: .roleType)
        try container.encode(roleName, forKey: .roleName)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(organizationId, forKey: .organizationId)
        try container.encode(active, forKey: .active)
        try container.encodeIfPresent(abbreviation, forKey: .abbreviation)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(lastModifiedBy, forKey: .lastModifiedBy)
        try container.encodeIfPresent(createdDate, forKey: .createdDate)
        try container.encodeIfPresent(lastModifiedDate, forKey: .lastModifiedDate)
    }
}

