//
// LastFour.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** dto body object to wrap last4 info and person uuid */
public struct LastFour: Codable, JSONEncodable, Hashable {

    /** first field of last4 field */
    public var last4: Int
    /** Confirmation of last4  */
    public var last4Confirmation: Int
    /** uuid of the person we are attempting to update the last4 of */
    public var personId: UUID

    public init(last4: Int, last4Confirmation: Int, personId: UUID) {
        self.last4 = last4
        self.last4Confirmation = last4Confirmation
        self.personId = personId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case last4
        case last4Confirmation
        case personId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(last4, forKey: .last4)
        try container.encode(last4Confirmation, forKey: .last4Confirmation)
        try container.encode(personId, forKey: .personId)
    }
}

