//
// MattermostChatUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** mattermost user returned by searching in roster form  */
public struct MattermostChatUser: Codable, JSONEncodable, Hashable {

    /**  */
    public var id: String
    /**  */
    public var username: String
    /**  */
    public var firstName: String
    /**  */
    public var lastName: String
    /**  */
    public var email: String?
    /**  */
    public var nickname: String?

    public init(id: String, username: String, firstName: String, lastName: String, email: String? = nil, nickname: String? = nil) {
        self.id = id
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.nickname = nickname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case nickname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(username, forKey: .username)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(nickname, forKey: .nickname)
    }
}

