//
// MattermostUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** mattermost user for confirmation by scheduler */
public struct MattermostUser: Codable, JSONEncodable, Hashable {

    /**  */
    public var firstName: String
    /**  */
    public var lastName: String
    /**  */
    public var email: String?
    /**  */
    public var username: String
    /**  */
    public var id: String

    public init(firstName: String, lastName: String, email: String? = nil, username: String, id: String) {
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.username = username
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName
        case lastName
        case email
        case username
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encode(username, forKey: .username)
        try container.encode(id, forKey: .id)
    }
}

