//
// MilitaryBranch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The branchs of the United States armed forces. */
public struct MilitaryBranch: Codable, JSONEncodable, Hashable {

    /** Puckboard ID of this branch of the armed forces */
    public var id: Int?
    /** Name of this branch of the armed forces */
    public var name: String?
    /** Organizations associated with this branch */
    public var organizations: [Organization]?
    /**  */
    public var ranks: [Rank]

    public init(id: Int? = nil, name: String? = nil, organizations: [Organization]? = nil, ranks: [Rank]) {
        self.id = id
        self.name = name
        self.organizations = organizations
        self.ranks = ranks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case organizations
        case ranks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(organizations, forKey: .organizations)
        try container.encode(ranks, forKey: .ranks)
    }
}

