//
// MissionEventType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct MissionEventType: Codable, JSONEncodable, Hashable {

    public var crewPosition: CrewPositionEnum?
    /**  */
    public var eventID: String
    /**  */
    public var isSim: Bool?
    /**  */
    public var name: String

    public init(crewPosition: CrewPositionEnum? = nil, eventID: String, isSim: Bool? = nil, name: String) {
        self.crewPosition = crewPosition
        self.eventID = eventID
        self.isSim = isSim
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case crewPosition
        case eventID
        case isSim
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(crewPosition, forKey: .crewPosition)
        try container.encode(eventID, forKey: .eventID)
        try container.encodeIfPresent(isSim, forKey: .isSim)
        try container.encode(name, forKey: .name)
    }
}

