//
// MissionForm781.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Mission with its corresponding form781s */
public struct MissionForm781: Codable, JSONEncodable, Hashable {

    /**  */
    public var form781s: [Form781]
    public var mission: Mission

    public init(form781s: [Form781], mission: Mission) {
        self.form781s = form781s
        self.mission = mission
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case form781s
        case mission
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(form781s, forKey: .form781s)
        try container.encode(mission, forKey: .mission)
    }
}

