//
// Mws.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** MWS information */
public struct Mws: Codable, JSONEncodable, Hashable {

    /** Major Weapons System (MWS) code */
    public var mws: String
    /** List of codes used to identify MDS or Type/Model/Series in REMIS data */
    public var remisCodes: [String]

    public init(mws: String, remisCodes: [String]) {
        self.mws = mws
        self.remisCodes = remisCodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mws
        case remisCodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mws, forKey: .mws)
        try container.encode(remisCodes, forKey: .remisCodes)
    }
}

