//
// MwsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List of all explicitly mapped &amp; supported Major Weapons System (MWS) types */
public struct MwsList: Codable, JSONEncodable, Hashable {

    /** List of all explicitly mapped & supported Major Weapons System (MWS) types */
    public var result: [Mws]

    public init(result: [Mws]) {
        self.result = result
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case result
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(result, forKey: .result)
    }
}

