//
// NewFeatureAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NewFeatureAllOf: Codable, JSONEncodable, Hashable {

    /** New feature name  */
    public var name: String
    /** Description of new feature  */
    public var description: String
    /** Svg file of new feature icon  */
    public var icon: String
    /** New feature id */
    public var id: UUID
    /** Time for new feature to stop being displayed on modal  */
    public var endTime: Date
    /** Date for feature to be displayed on modal  */
    public var startTime: Date

    public init(name: String, description: String, icon: String, id: UUID, endTime: Date, startTime: Date) {
        self.name = name
        self.description = description
        self.icon = icon
        self.id = id
        self.endTime = endTime
        self.startTime = startTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case icon
        case id
        case endTime
        case startTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(icon, forKey: .icon)
        try container.encode(id, forKey: .id)
        try container.encode(endTime, forKey: .endTime)
        try container.encode(startTime, forKey: .startTime)
    }
}

