//
// OffloadAircraft.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct OffloadAircraft: Codable, JSONEncodable, Hashable {

    /**  */
    public var aircraftCallSign: String?
    /**  */
    public var aircraftCommand: String?
    /**  */
    public var aircraftDodaac: String?
    /**  */
    public var aircraftHomeStation: String?
    /**  */
    public var aircraftNumber: String?
    /**  */
    public var aircraftOrganization: String?
    /**  */
    public var aircraftType: String?
    /**  */
    public var dateCreated: Date?
    public var id: UUID?
    /**  */
    public var airRefuelEvents: [AirRefuelEvent]?

    public init(aircraftCallSign: String? = nil, aircraftCommand: String? = nil, aircraftDodaac: String? = nil, aircraftHomeStation: String? = nil, aircraftNumber: String? = nil, aircraftOrganization: String? = nil, aircraftType: String? = nil, dateCreated: Date? = nil, id: UUID? = nil, airRefuelEvents: [AirRefuelEvent]? = nil) {
        self.aircraftCallSign = aircraftCallSign
        self.aircraftCommand = aircraftCommand
        self.aircraftDodaac = aircraftDodaac
        self.aircraftHomeStation = aircraftHomeStation
        self.aircraftNumber = aircraftNumber
        self.aircraftOrganization = aircraftOrganization
        self.aircraftType = aircraftType
        self.dateCreated = dateCreated
        self.id = id
        self.airRefuelEvents = airRefuelEvents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aircraftCallSign
        case aircraftCommand
        case aircraftDodaac
        case aircraftHomeStation
        case aircraftNumber
        case aircraftOrganization
        case aircraftType
        case dateCreated
        case id
        case airRefuelEvents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(aircraftCallSign, forKey: .aircraftCallSign)
        try container.encodeIfPresent(aircraftCommand, forKey: .aircraftCommand)
        try container.encodeIfPresent(aircraftDodaac, forKey: .aircraftDodaac)
        try container.encodeIfPresent(aircraftHomeStation, forKey: .aircraftHomeStation)
        try container.encodeIfPresent(aircraftNumber, forKey: .aircraftNumber)
        try container.encodeIfPresent(aircraftOrganization, forKey: .aircraftOrganization)
        try container.encodeIfPresent(aircraftType, forKey: .aircraftType)
        try container.encodeIfPresent(dateCreated, forKey: .dateCreated)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(airRefuelEvents, forKey: .airRefuelEvents)
    }
}

