//
// OrganizationStatusAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrganizationStatusAllOf: Codable, JSONEncodable, Hashable {

    /** boolean to determine the status of a person for an organization from the person's perspective. */
    public var active: Bool
    /**  */
    public var organizationId: UUID?
    /**  */
    public var jobRoleId: Int?

    public init(active: Bool, organizationId: UUID? = nil, jobRoleId: Int? = nil) {
        self.active = active
        self.organizationId = organizationId
        self.jobRoleId = jobRoleId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case active
        case organizationId
        case jobRoleId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(active, forKey: .active)
        try container.encodeIfPresent(organizationId, forKey: .organizationId)
        try container.encodeIfPresent(jobRoleId, forKey: .jobRoleId)
    }
}

