//
// PageableTrainingTasksList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct PageableTrainingTasksList: Codable, JSONEncodable, Hashable {

    /**  */
    public var result: [PblTrainingTask]
    /** page number of the data */
    public var page: Int?
    /** current page size */
    public var size: Int?
    /** total number of elements that reside in the database */
    public var totalElements: Int64?
    /** total pages that can be rendered */
    public var totalPages: Int?

    public init(result: [PblTrainingTask], page: Int? = nil, size: Int? = nil, totalElements: Int64? = nil, totalPages: Int? = nil) {
        self.result = result
        self.page = page
        self.size = size
        self.totalElements = totalElements
        self.totalPages = totalPages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case result
        case page
        case size
        case totalElements
        case totalPages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(result, forKey: .result)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(totalElements, forKey: .totalElements)
        try container.encodeIfPresent(totalPages, forKey: .totalPages)
    }
}

