//
// PblRemisTailList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List of remis tails */
public struct PblRemisTailList: Codable, JSONEncodable, Hashable {

    /**      */
    public var result: [PblRemisTail]

    public init(result: [PblRemisTail]) {
        self.result = result
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case result
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(result, forKey: .result)
    }
}

