//
// PblTimeCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Time Category for events */
public struct PblTimeCategory: Codable, JSONEncodable, Hashable {

    /** String code representing time category */
    public var code: String
    /** String name of the time category */
    public var name: String

    public init(code: String, name: String) {
        self.code = code
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(name, forKey: .name)
    }
}

