//
// PersonUploadResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result details from a batch personnel upload */
public struct PersonUploadResult: Codable, JSONEncodable, Hashable {

    /**  */
    public var uploadedPeople: [UploadedPerson]
    /** Total new people uploaded successfully */
    public var totalCreated: Int64
    /** Total not newly created - either errored or existed already */
    public var totalNotCreated: Int64

    public init(uploadedPeople: [UploadedPerson], totalCreated: Int64, totalNotCreated: Int64) {
        self.uploadedPeople = uploadedPeople
        self.totalCreated = totalCreated
        self.totalNotCreated = totalNotCreated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uploadedPeople
        case totalCreated
        case totalNotCreated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uploadedPeople, forKey: .uploadedPeople)
        try container.encode(totalCreated, forKey: .totalCreated)
        try container.encode(totalNotCreated, forKey: .totalNotCreated)
    }
}

