//
// RankAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RankAllOf: Codable, JSONEncodable, Hashable {

    /** The name of this rank */
    public var rankName: String
    /** The pay scale for this rank. */
    public var payGrade: String
    /** The abbreviation of the rank name. */
    public var rankAbbr: String
    /** Delineates if a rank is Enlisted, Warrant Officer, or Officer. */
    public var rankStatus: String
    /**  */
    public var rankId: Int

    public init(rankName: String, payGrade: String, rankAbbr: String, rankStatus: String, rankId: Int) {
        self.rankName = rankName
        self.payGrade = payGrade
        self.rankAbbr = rankAbbr
        self.rankStatus = rankStatus
        self.rankId = rankId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rankName
        case payGrade
        case rankAbbr
        case rankStatus
        case rankId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rankName, forKey: .rankName)
        try container.encode(payGrade, forKey: .payGrade)
        try container.encode(rankAbbr, forKey: .rankAbbr)
        try container.encode(rankStatus, forKey: .rankStatus)
        try container.encode(rankId, forKey: .rankId)
    }
}

