//
// RoleEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum RoleEnum: String, Codable, CaseIterable {
    case mx = "MX"
    case ado = "ADO"
    case sarm = "SARM"
}
