//
// RoleAssignmentNoteAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RoleAssignmentNoteAllOf: Codable, JSONEncodable, Hashable {

    /**  */
    public var id: UUID?
    /**  */
    public var note: String?

    public init(id: UUID? = nil, note: String? = nil) {
        self.id = id
        self.note = note
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case note
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(note, forKey: .note)
    }
}

