//
// ScheduleAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScheduleAllOf: Codable, JSONEncodable, Hashable {

    /** The job role compatibility hierarchy for the associated squadron. */
    public var jobRoles: [JobRoleCompatibility]?
    /** The personnel available for scheduling within the associated squadron. */
    public var personnel: [Person]?
    /** The types of events that need to be scheduled within the associated squadron. */
    public var eventTypes: [EventType]?
    /** The events that need to be scheduled within the associated squadron. */
    public var events: [EventBase]?

    public init(jobRoles: [JobRoleCompatibility]? = nil, personnel: [Person]? = nil, eventTypes: [EventType]? = nil, events: [EventBase]? = nil) {
        self.jobRoles = jobRoles
        self.personnel = personnel
        self.eventTypes = eventTypes
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobRoles
        case personnel
        case eventTypes
        case events
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(jobRoles, forKey: .jobRoles)
        try container.encodeIfPresent(personnel, forKey: .personnel)
        try container.encodeIfPresent(eventTypes, forKey: .eventTypes)
        try container.encodeIfPresent(events, forKey: .events)
    }
}

