//
// SortieFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** data pertaining to a flag on a sortie */
public struct SortieFlag: Codable, JSONEncodable, Hashable {

    /** error data description */
    public var data: String?
    /** detailed message describing error */
    public var detail: String?
    /** notes left by aircrew pertaining to flag */
    public var aircrewNotes: String?
    /** notes left by ado pertaining to flag */
    public var adoNotes: String?
    /** notes left by sarm pertaining to flag */
    public var sarmNotes: String?
    /** uuid of a flag generated by pbs */
    public var id: UUID?
    /** uuid of sortie the flag is on */
    public var pblSortieId: UUID?

    public init(data: String? = nil, detail: String? = nil, aircrewNotes: String? = nil, adoNotes: String? = nil, sarmNotes: String? = nil, id: UUID? = nil, pblSortieId: UUID? = nil) {
        self.data = data
        self.detail = detail
        self.aircrewNotes = aircrewNotes
        self.adoNotes = adoNotes
        self.sarmNotes = sarmNotes
        self.id = id
        self.pblSortieId = pblSortieId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case detail
        case aircrewNotes
        case adoNotes
        case sarmNotes
        case id
        case pblSortieId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(aircrewNotes, forKey: .aircrewNotes)
        try container.encodeIfPresent(adoNotes, forKey: .adoNotes)
        try container.encodeIfPresent(sarmNotes, forKey: .sarmNotes)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(pblSortieId, forKey: .pblSortieId)
    }
}

