//
// SubCategoryType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Types a subcategory can be */
public enum SubCategoryType: String, Codable, CaseIterable {
    case freeText = "FREE_TEXT"
    case personList = "PERSON_LIST"
    case eventBased = "EVENT_BASED"
    case roleAvailability = "ROLE_AVAILABILITY"
}
