//
// SubCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct SubCategory: Codable, JSONEncodable, Hashable {

    public var header: String
    public var kind: SubCategoryType
    public var entityTypeId: Int?
    public var bgColor: String?
    public var order: Int
    public var labels: [FreeTextLabel]

    public init(header: String, kind: SubCategoryType, entityTypeId: Int? = nil, bgColor: String? = nil, order: Int, labels: [FreeTextLabel]) {
        self.header = header
        self.kind = kind
        self.entityTypeId = entityTypeId
        self.bgColor = bgColor
        self.order = order
        self.labels = labels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case header
        case kind
        case entityTypeId
        case bgColor
        case order
        case labels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(header, forKey: .header)
        try container.encode(kind, forKey: .kind)
        try container.encodeIfPresent(entityTypeId, forKey: .entityTypeId)
        try container.encodeIfPresent(bgColor, forKey: .bgColor)
        try container.encode(order, forKey: .order)
        try container.encode(labels, forKey: .labels)
    }
}

