//
// UserState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct UserState: Codable, JSONEncodable, Hashable {

    /**  */
    public var personnelFilter: AnyCodable?
    /**  */
    public var eventTypesFilter: AnyCodable?

    public init(personnelFilter: AnyCodable? = nil, eventTypesFilter: AnyCodable? = nil) {
        self.personnelFilter = personnelFilter
        self.eventTypesFilter = eventTypesFilter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case personnelFilter
        case eventTypesFilter
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(personnelFilter, forKey: .personnelFilter)
        try container.encodeIfPresent(eventTypesFilter, forKey: .eventTypesFilter)
    }
}

